### ISSUE TITLE
[Feature Request] Create a note inside a New Folder -> Keyboard Hotkey Helper

### ISSUE THREAD

**Issue by FelipeRearden** [vanadium23/obsidian-advanced-new-file#11]
Hello @vanadium23 !!!

My Fr is simple to explain: it's a keyboard hotkey that **copies** the folder that is focused in the modal. 

This would help us when we want to create a a new note folder inside a new folder

## Workflow

My Folder `11 Books` is the foder that have all my books. Every Book has it's own folder 

For example:

11 Books
|--> 11.01 Atomic Habits
|--> 11.02 How to Take Smart Notes
....

I'm start a new Book called **The Obstacle is the way** and I need to create a new note inside a new folder 

As you can see from the image above, the modal is focused in the line `11 Books` 

![image](https://user-images.githubusercontent.com/85180696/166522555-319ab454-06c8-4f80-b7f5-70ded99a9706.jpeg)

My FR is an keyboard hotkey to paste the word `11 Books/` **inside** the text field.

![image](https://user-images.githubusercontent.com/85180696/166522587-41ab0919-d20e-443f-8cd0-5a4d57a9d6da.jpeg)

➡️ My suggestion is the `TAB` key for this

This way I can easily type `11.03 The Obstacle in the Way` and create a new note inside a new folder :)

---

Let me know if you need more information 

Thanks for reading this and have a great day !!!!

**Comment by vanadium23** [comment]
Great request, I'll take a look :+1:

**Comment by FelipeRearden** [comment]
Thank you very much @vanadium23 !!!!!!!!!

**Comment by vanadium23** [comment]
Is everything fine?


https://user-images.githubusercontent.com/2872741/167003087-7cd696d1-3b1c-416f-b61a-d4a191e8e40e.mp4

**Comment by FelipeRearden** [comment]
> Is everything fine?

Looks amazing @vanadium23 !!!!

Thank you very much !!!!

My only question is it will work if I'm focused in a line different from the first 

In your video you are using the keyboard to select the first folder (11 Books) than hitting TAB to complete 

When we have the new version, I will do the test for the two possible user operation :)


thank for making this real :)

**Comment by vanadium23** [comment]
Yes, TAB autocompletes from the selection. So you can choose another folder, and hit TAB.

**Comment by vanadium23** [comment]
Released version 1.3.0.

**Comment by FelipeRearden** [comment]
Hello @vanadium23 !!!!

Spectacular !!!!! Working perfect on Obsdidan version 0.14.6 !!!!

Thank you very much for this new feature :)

Have a great day !!!!
