### ISSUE TITLE
New file opens in file explorer

### ISSUE THREAD

**Issue by cleobis** [vanadium23/obsidian-advanced-new-file#15]
I ran into an issue where the newly created file is opened in the file explorer pane rather than the currently active document pane. It appears to be the same issue described for another plugin at https://github.com/SilentVoid13/Templater/issues/691. The fix described in that link seems to work for Advanced New File too. Namely, change main.js at line 186:
```javascript
/* Current code:
yield this.app.workspace.activeLeaf.openFile(File);
*/
// Fix:
const active_leaf = yield this.app.workspace.getLeaf(false);
if (!active_leaf) {
    throw new Error("No active leaf");
}
active_leaf.openFile(File);
```

Versions:
- Advanced New File v 1.4.1
- Obsidian v 1.0.3
- Obsidian Installer v 1.0.0

**Comment by vanadium23** [comment]
Thanks for reporting, I'll take a look.
