### ISSUE TITLE
Create file based on full path

### ISSUE THREAD

**Issue by vanadium23** [vanadium23/obsidian-advanced-new-file#2]
Add alternative command, where user can input `foo/bar/baz` and note `baz` will be created in folder `foo/bar`.
Think about autocomplete in input for folders.

**Comment by MaciejWiatr** [comment]
any updates on that one? :)

**Comment by vanadium23** [comment]
This is just an idea, I really don't think about how to implement it. :(
If you have any suggestion, feel free to post in issue.

**Comment by vanadium23** [comment]
Wow, thanks!
I would love to take a look and merge, if everything works the way you described. :+1:

**Comment by lukePeavey** [comment]
Sounds good. I'll submit a PR this week

**Comment by vanadium23** [comment]
Release version 1.2.0 with feature from @lukePeavey. I think we can close the issue. :tada:
