### ISSUE TITLE
[Bug] Creating a new file while inside a note moves the page content down three lines

### ISSUE THREAD

**Issue by harttraveller** [vanadium23/obsidian-advanced-new-file#23]
Love your plugin!

Starting note

<img width="492" alt="2023-02-08 at 11 36 33" src="https://user-images.githubusercontent.com/24962209/217593322-19899393-ed68-42f0-bd86-350d97a3ed10.png">

after creating a new note

<img width="412" alt="2023-02-08 at 11 37 13" src="https://user-images.githubusercontent.com/24962209/217593489-7ed926ac-8829-45dc-9537-15f4f5cd1e0f.png">

Is there a setting I can turn off to address this? I listed it as a bug as I can't see what feature is offered.

**Comment by vanadium23** [comment]
Yes, it's bug, but i don't know how it reproduce it :(

**Comment by harttraveller** [comment]
Haha fair enough lol.
