### ISSUE TITLE
Plugin ID mismatch

### ISSUE THREAD

**Issue by superouioui** [vanadium23/obsidian-advanced-new-file#4]
When I want install from Obsidian. I have the message: Plugin ID mismatch.
And nothing is installed.

**Comment by vanadium23** [comment]
Hi, @superouioui.

I've tested it against an empty vault and receive no such error.

Can you provide more details?

![image](https://user-images.githubusercontent.com/2872741/160672204-e88dfc16-ce95-4303-8f5f-ba13dbcfda5b.png)

**Comment by vanadium23** [comment]
Triaged.
