### ISSUE TITLE
[chore] update plugin template

### ISSUE THREAD

**Issue by lukePeavey** [vanadium23/obsidian-advanced-new-file#6]
Update plugin configuration to match the latest version of [Obsidian Plugin Template](https://github.com/obsidianmd/obsidian-sample-plugin).  

Changes: 

- Switch from rollup to esbuild. (see [esbuild.config.mjs](https://github.com/obsidianmd/obsidian-sample-plugin/blob/master/esbuild.config.mjs))
- Update obsidian api version
- Add eslint config

If you want, I'd be happy to submit a PR. If not, feel free to close this.

**Comment by vanadium23** [comment]
Would love to see it.
