### ISSUE TITLE
Create new file replaces Pinned file

### ISSUE THREAD

**Issue by pdelre** [vanadium23/obsidian-advanced-new-file#9]
When the active pane is Pinned with an existing file, when creating a new file, the new file is then opened in the Pinned pane, replacing the previously Pinned file. I'd expect that instead the new file is opened in a new pane which matches the native "Create new note" functionality.

I'm creating this separate from #3 as revolves around pinned panes where there's less likely a need to configure the expected behavior (never replace an intentionally pinned view).

**Comment by vanadium23** [comment]
A new release 1.4.0 includes the command to create in a new pane. Can we close the issue or you want to have another solution?

**Comment by pdelre** [comment]
Yes, the second command resolves this alternate view of #3 as well.
